# Generated by Django 3.0.3 on 2020-05-18 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_drive', 'can drive')]},
        ),
    ]
